# SOAL 1

In [ ]:
import numpy as np

iniArray = np.array([[4, 4, 5],
                     [7, 6, 4],
                     [9, 7, 4],
                     [6, 3, 7]])

print(iniArray)
print("array di atas merupakan array",iniArray.ndim,"dimensi")

[[4 4 5]
 [7 6 4]
 [9 7 4]
 [6 3 7]]
array di atas merupakan array 2 dimensi


# SOAL 2

In [41]:
iniArray = np.array([[[7, 8, 5], [4, 7, 7], [7, 1, 9], [5, 4, 10]],
                      [[2, 1, 2], [9, 8, 5], [3, 7 ,3], [4, 9, 9]],
                      [[2, 9, 3], [2, 4, 8], [1, 6, 6], [8, 1, 3]]])

print(iniArray)
print("array di atas merupakan array",iniArray.ndim,"dimensi")

[[[ 7  8  5]
  [ 4  7  7]
  [ 7  1  9]
  [ 5  4 10]]

 [[ 2  1  2]
  [ 9  8  5]
  [ 3  7  3]
  [ 4  9  9]]

 [[ 2  9  3]
  [ 2  4  8]
  [ 1  6  6]
  [ 8  1  3]]]
array di atas merupakan array 3 dimensi


# SOAL 3

In [42]:
iniArray = np.array([[1, 8, 8, 2],
                      [8, 2, 1, 2],
                      [10, 1, 4, 7],
                      [1, 4, 7, 8],
                      [8, 2, 3, 4]])
print("array awal:\n",iniArray)

array1 = iniArray.copy()
array1[::2] += 1
print("tambah angka 1 pada baris ganjil:\n",array1)

array2 = array1.copy()
array2[:, 1::2] += 2
print("tambah angka 2 pada kolom genap:\n",array2)

array awal:
 [[ 1  8  8  2]
 [ 8  2  1  2]
 [10  1  4  7]
 [ 1  4  7  8]
 [ 8  2  3  4]]
tambah angka 1 pada baris ganjil:
 [[ 2  9  9  3]
 [ 8  2  1  2]
 [11  2  5  8]
 [ 1  4  7  8]
 [ 9  3  4  5]]
tambah angka 2 pada kolom genap:
 [[ 2 11  9  5]
 [ 8  4  1  4]
 [11  4  5 10]
 [ 1  6  7 10]
 [ 9  5  4  7]]


# SOAL 4

In [49]:
iniArray = np.array([[[7, 8, 5], [4, 7, 7], [7, 1, 9], [5, 4, 10]],
                      [[2, 1, 2], [9, 8, 5], [3, 7 ,3], [4, 9, 9]],
                      [[2, 9, 3], [2, 4, 8], [1, 6, 6], [8, 1, 3]]])
arrayDibolak = np.flip(iniArray, axis=2)
print(arrayDibolak)

[[[ 5  8  7]
  [ 7  7  4]
  [ 9  1  7]
  [10  4  5]]

 [[ 2  1  2]
  [ 5  8  9]
  [ 3  7  3]
  [ 9  9  4]]

 [[ 3  9  2]
  [ 8  4  2]
  [ 6  6  1]
  [ 3  1  8]]]


# SOAL 5

In [50]:
iniArray = np.array([[[7, 8, 5], [4, 7, 7], [7, 1, 9], [5, 4, 10]],
                      [[2, 1, 2], [9, 8, 5], [3, 7 ,3], [4, 9, 9]],
                      [[2, 9, 3], [2, 4, 8], [1, 6, 6], [8, 1, 3]]])

jadiGepeng = iniArray.reshape(6, 6)
print("array setelah direshape menjadi 6x6:\n", jadiGepeng)

array setelah direshape menjadi 6x6:
 [[ 7  8  5  4  7  7]
 [ 7  1  9  5  4 10]
 [ 2  1  2  9  8  5]
 [ 3  7  3  4  9  9]
 [ 2  9  3  2  4  8]
 [ 1  6  6  8  1  3]]


# SOAL 6

In [ ]:
arrayKiri = np.array(
                    [
                        [5, 10, 10, 7],
                        [7, 8, 4, 10],
                        [9, 10, 2, 5],
                        [1, 8, 9, 3],
                        [6, 10, 5, 2],
                        [4, 6, 9, 4]
                    ])
arrayKanan = np.array([[9, 3, 1, 8],
                    [5, 2, 6, 10],
                    [9, 4, 4, 6],
                    [10, 7, 5, 10],
                    [4, 10, 7, 8],
                    [2, 5, 9, 10]])

flatKiri = arrayKiri.flatten()
flatKanan = arrayKanan.flatten()
a= np.sort(flatKiri)
b= np.sort(flatKanan)
print(a)
print(b)
print(flatKiri)
print(flatKanan)

indeksTersedia = {i: [] for i in range(len(flatKiri))}
for i, nilai in enumerate(flatKiri):
    indeksTersedia[nilai].append(i)

indeksPermutasi = []
for nilai in flatKanan:
    indeksPermutasi.append(indeksTersedia[nilai].pop(0))

arrayKiriDiubah = flatKiri[indeksPermutasi].reshape(arrayKiri.shape)

print("Indeks pemetaan dari arrayKiri ke arrayKanan:", indeksPermutasi)
print("arrayKiri setelah dikonversi menjadi arrayKanan:\n", arrayKiriDiubah)

[ 1  2  2  3  4  4  4  5  5  5  6  6  7  7  8  8  9  9  9 10 10 10 10 10]
[ 1  2  2  3  4  4  4  5  5  5  6  6  7  7  8  8  9  9  9 10 10 10 10 10]
[ 5 10 10  7  7  8  4 10  9 10  2  5  1  8  9  3  6 10  5  2  4  6  9  4]
[ 9  3  1  8  5  2  6 10  9  4  4  6 10  7  5 10  4 10  7  8  2  5  9 10]
Indeks pemetaan dari arrayKiri ke arrayKanan: [8, 15, 12, 5, 0, 10, 16, 1, 14, 6, 20, 21, 2, 3, 11, 7, 23, 9, 4, 13, 19, 18, 22, 17]
arrayKiri setelah dikonversi menjadi arrayKanan:
 [[ 9  3  1  8]
 [ 5  2  6 10]
 [ 9  4  4  6]
 [10  7  5 10]
 [ 4 10  7  8]
 [ 2  5  9 10]]
